
package View;

import Controller.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class GeneraCuenta extends javax.swing.JFrame {

    /**
     * Creates new form IngresosEgresos
     */
    public GeneraCuenta(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RFC = new javax.swing.JTextField();
        limpia = new javax.swing.JButton();
        imprime = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nombrePac = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        muestraCuenta = new javax.swing.JTextArea();
        ape1 = new javax.swing.JLabel();
        ape2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("RFC");

        RFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RFCKeyPressed(evt);
            }
        });

        limpia.setText("Limpiar");
        limpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiaActionPerformed(evt);
            }
        });

        imprime.setText("Imprimir");

        jLabel4.setText("Nombre Del Paciente:");

        muestraCuenta.setColumns(20);
        muestraCuenta.setRows(5);
        jScrollPane2.setViewportView(muestraCuenta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limpia)
                    .addComponent(imprime)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RFC, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ape1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombrePac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                    .addComponent(ape2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(RFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombrePac, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ape1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ape2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(imprime)
                        .addGap(18, 18, 18)
                        .addComponent(limpia))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RFCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RFCKeyPressed
        if(evt.getKeyCode() == 27){
            try {
                muestraCuenta.setText("");
                generaCuenta();
            } catch (SQLException ex) {
                Logger.getLogger(GeneraCuenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_RFCKeyPressed

    private void limpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiaActionPerformed
        RFC.setText("");
        muestraCuenta.setText("");
    }//GEN-LAST:event_limpiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneraCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneraCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneraCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneraCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneraCuenta().setVisible(true);
            }
        });
    }
    
    private void generaCuenta() throws SQLException{
        
        ConexionBD con = new ConexionBD();
        Connection conecta;
        PreparedStatement ps;
        ResultSet res;
        String fechaIngreso = null;
        float total = 0;
        
        conecta = con.getConnection();
        
        ps = conecta.prepareStatement("SELECT NombrePac, Apellido1, Apellido2, FechaIngreso FROM ingreso_piso WHERE RFC = (?)");
        ps.setString(1, RFC.getText());
        
        res = ps.executeQuery();
        
        if(res.next()){
            nombrePac.setText(res.getString("NombrePac"));
            ape1.setText(res.getString("Apellido1"));
            ape2.setText(res.getString("Apellido2"));
            fechaIngreso = res.getString("FechaIngreso");
        }
        
        ps = conecta.prepareStatement("SELECT * FROM ventas WHERE RFCPac = (?) AND fecha > (?)");
        
        ps.setString(1,  RFC.getText());
        ps.setString(2, fechaIngreso);
        
        res = ps.executeQuery();
        
        if(res.next()){
            do{
                muestraCuenta.append(res.getString("fecha") + "  ");
                muestraCuenta.append(res.getString("nombre") + "-------");
                muestraCuenta.append("$" + res.getString("costo") + "\n");
                total = total + res.getFloat("costo");
            }
            while(res.next());

            muestraCuenta.append("\nTotal: $" + total);
        }
        else{
            JOptionPane.showMessageDialog(null, "Paciente NO registrado", "Cuenta No Generada", JOptionPane.ERROR_MESSAGE);
        }
        
        conecta.close();
    }
    
//    private void restringeFechas(){
//        
//        fecha y hora del sistema
//        Date now = new Date(System.currentTimeMillis());
//        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
//        SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
//
//        System.out.println(date.format(now));
//        System.out.println(hour.format(now));
//        System.out.println(now);
//        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
//        Date fe = new Date(System.currentTimeMillis());
//        Date fe1 = null;
//        
//        prueba.setMaxSelectableDate(fe);
//        prueba.setMinSelectableDate(fe1);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RFC;
    private javax.swing.JLabel ape1;
    private javax.swing.JLabel ape2;
    private javax.swing.JButton imprime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpia;
    private javax.swing.JTextArea muestraCuenta;
    private javax.swing.JLabel nombrePac;
    // End of variables declaration//GEN-END:variables
}
