package View;

import Controller.My_CNX;
import java.awt.Color;
import java.awt.Frame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class LoginForm extends javax.swing.JFrame {
    private String usuario;
    private String contraseña;
    public static String user;
    public static String jerarquia;
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        jLabel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWallpaper = new javax.swing.JLabel();
        JLabelUserName = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jPanelWaiting = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jPanelExit = new javax.swing.JPanel();
        jLabelWaiting = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Login.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        JLabelUserName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLabelUserName.setForeground(new java.awt.Color(255, 255, 255));
        JLabelUserName.setText("Username: ");

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Password:");

        jTextFieldUserName.setBackground(new java.awt.Color(0, 153, 153));
        jTextFieldUserName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldUserName.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUserNameFocusLost(evt);
            }
        });
        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });

        jPasswordField.setBackground(new java.awt.Color(0, 153, 153));
        jPasswordField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jButtonLogin.setBackground(new java.awt.Color(0, 153, 153));
        jButtonLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("LOGIN");
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseExited(evt);
            }
        });
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jPanelWaiting.setBackground(new java.awt.Color(0, 102, 102));
        jPanelWaiting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanelWaiting.setForeground(new java.awt.Color(255, 255, 255));

        jLabelExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setText("x");
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelWaitingLayout = new javax.swing.GroupLayout(jPanelWaiting);
        jPanelWaiting.setLayout(jPanelWaitingLayout);
        jPanelWaitingLayout.setHorizontalGroup(
            jPanelWaitingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWaitingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWaitingLayout.setVerticalGroup(
            jPanelWaitingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWaitingLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelExit))
        );

        jPanelExit.setBackground(new java.awt.Color(0, 102, 102));
        jPanelExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabelWaiting.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelWaiting.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWaiting.setText("-");
        jLabelWaiting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelWaitingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelExitLayout = new javax.swing.GroupLayout(jPanelExit);
        jPanelExit.setLayout(jPanelExitLayout);
        jPanelExitLayout.setHorizontalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWaiting)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelExitLayout.setVerticalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelWaiting))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Olvidaste tu contraseña");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel2)
                        .addGap(410, 410, 410)
                        .addComponent(jPanelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabelPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(670, 670, 670)
                        .addComponent(jPanelWaiting, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(JLabelUserName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2))
                            .addComponent(jPanelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabelPassword)
                        .addGap(31, 31, 31)
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanelWaiting, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(JLabelUserName)))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jTextFieldUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUserNameFocusGained
        
        if( jTextFieldUserName.getText( ).trim().toLowerCase().equals("username") ){
            jTextFieldUserName.setText("");
            jTextFieldUserName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldUserNameFocusGained

    private void jTextFieldUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUserNameFocusLost
        
    }//GEN-LAST:event_jTextFieldUserNameFocusLost

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        
        PreparedStatement st;
        ResultSet rs;
        
        //get the username and password
        String username = jTextFieldUserName.getText();
        String password = String.valueOf(jPasswordField.getPassword());
        
        //query: compare if we have the same information in the boxes with our database
        String query = "SELECT jerarquia FROM `login` WHERE `usuario`= ? AND `contraseña` = ? ";
        
        try {
            st = My_CNX.getConnection().prepareStatement(query);
            
            st.setString(1,username);
            st.setString(2,password);
            
            rs = st.executeQuery();
            
            if( rs.next() ){
                jerarquia=rs.getString("jerarquía");
                if(jerarquia!="0"){
                    PrincipalMenu form = new PrincipalMenu();
                    form.setVisible(true);
                    form.pack();
                    form.setLocationRelativeTo(null);
                }else{
                    new MenuUsuarios().setVisible(true);
                }
               
                
                //closing
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Invalid user / password");
            }
                    
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseEntered
        jButtonLogin.setBackground(new Color(0,153,153) );
    }//GEN-LAST:event_jButtonLoginMouseEntered
    
    private void jButtonLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseExited
        jButtonLogin.setBackground(new Color(0,102,102) );
    }//GEN-LAST:event_jButtonLoginMouseExited

    private void jLabelWaitingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelWaitingMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelWaitingMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet rs;
        
        String correo=JOptionPane.showInputDialog(null,"Escriba su correo electronico");
        buscarCorreo(correo);
        if(jLabel2.getText()!=""){
            String pass="ingenieria";
            String correoEnvia="clinica.manager19";

            String asunto="Recuperacion de contrasena";
            Properties propiedad=new Properties();
            propiedad.setProperty("mail.smtp.host","smtp.gmail.com");//tipo de correo
            propiedad.setProperty("mail.smtp.starttls.enable","true");//habilita el inicio de sesion
            propiedad.setProperty("mail.smtp.port","587");//puerto de gmail
            propiedad.setProperty("mail.smtp.auth","true");//inicia sesion automaticamente

            Session sesion= Session.getDefaultInstance(propiedad);
            MimeMessage mail=new MimeMessage(sesion);
            int numero = (int)(Math.random()*(999-100+1)*100);
            int numeroIngresar;
            String mensaje="Ingrese este numero "+numero+" para poder validar la recuperacion de contrasena";
            try {
                mail.setFrom(new InternetAddress(correoEnvia));
                mail.addRecipient(Message.RecipientType.TO,new InternetAddress(correo));
                mail.setSubject(asunto);
                mail.setText(mensaje);

                Transport transporte = sesion.getTransport("smtp");
                transporte.connect(correoEnvia,pass);
                transporte.sendMessage(mail,mail.getRecipients(Message.RecipientType.TO));
                transporte.close();


            } catch (AddressException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MessagingException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            } 
            numeroIngresar=Integer.parseInt(JOptionPane.showInputDialog(null,"Se le mando a su correo un mensaje que contiene unos digitos.\nIngrese los digitos en este campo"));
            
                if(numeroIngresar==numero){
                    this.dispose();
                    new NuevaContrasena().setVisible(true);
                }else
                {
                    JOptionPane.showMessageDialog(null,"Codigo invorrecto","Error",JOptionPane.ERROR_MESSAGE);
                }
           
            
        
        }else{
            JOptionPane.showMessageDialog(null,"Su correo que registro esta incorrecto o no esta registrado","Error",JOptionPane.ERROR_MESSAGE);
        }
       
        
        
    }//GEN-LAST:event_jLabel1MouseClicked

    
    private void buscarCorreo(String correo){
        PreparedStatement ps;
        ResultSet rs;
        String query="Select usuario,email from login where email='"+correo+"'";
        try {
            ps = My_CNX.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            if (rs != null) {
           
              try {
                   
                   
                  while (rs.next()) {
                        Object dato[]=new Object[4];
                            user=rs.getString("usuario");
                            jLabel2.setText(rs.getString("email"));
                        
                  } 
             
              } catch (SQLException ex) {
                  //Logger.getLogger(I_Medicamentos.class.getName()).log(Level.SEVERE, null, ex);
                  System.out.println(ex);
              }
           
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelUserName;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelWaiting;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JPanel jPanelExit;
    private javax.swing.JPanel jPanelWaiting;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
