
package View;

import Controller.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class ReporteIngresos extends javax.swing.JFrame {

    /**
     * Creates new form ReporteIngresos
     */
    public ReporteIngresos() {
        initComponents();
        restringeFechas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fechaDe = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        fechaA = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        limpia = new javax.swing.JButton();
        imprime = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        muestraR = new javax.swing.JTextArea();
        consulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("De");

        jLabel2.setText("A");

        jLabel3.setText("Reporte de Ingresos");

        limpia.setText("Limpiar");
        limpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiaActionPerformed(evt);
            }
        });

        imprime.setText("Imprimir");

        muestraR.setColumns(20);
        muestraR.setRows(5);
        jScrollPane1.setViewportView(muestraR);

        consulta.setText("Consultar");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(limpia)
                            .addComponent(imprime)
                            .addComponent(jLabel3)
                            .addComponent(consulta))
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fechaA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(fechaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(consulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(imprime)
                        .addGap(18, 18, 18)
                        .addComponent(limpia)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        try {
            generaReporte();
        } catch (SQLException ex) {
            Logger.getLogger(ReporteIngresos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_consultaActionPerformed

    private void limpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiaActionPerformed
        fechaA.setDate(null);
        fechaDe.setDate(null);
        muestraR.setText("");
    }//GEN-LAST:event_limpiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteIngresos().setVisible(true);
            }
        });
    }
    
    private void generaReporte() throws SQLException{
        
        ConexionBD con = new ConexionBD();
        Connection conecta;
        PreparedStatement ps;
        ResultSet res;
        String de, a;
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        float total = 0;
        
        de = format.format(fechaDe.getDate());
        a = format.format(fechaA.getDate());
        
        conecta = con.getConnection();
        
        ps = conecta.prepareStatement("SELECT idServicio, provedor, fecha, hospital FROM venta_consolidad WHERE fecha >= (?) AND fecha <= (?)");
        ps.setString(1, de);
        ps.setString(2, a);
        
        res = ps.executeQuery();
        
        if(res.next()){
            do{
                muestraR.append(res.getString("fecha") + "  ");
                muestraR.append(res.getString("idServicio") + " ");
                muestraR.append(res.getString("provedor") + "--------");
                muestraR.append("$" + res.getString("hospital") + "\n");
                total = total + res.getFloat("hospital");
            }
            while(res.next());

            muestraR.append("\nTotal: $" + total);
        }
        else{
            JOptionPane.showMessageDialog(null, "No se encontro Registros en Las fechas solicitadas", "Informe No Generado", JOptionPane.ERROR_MESSAGE);
        }
        
        conecta.close();
    }
    
    private void restringeFechas(){
        
//        fecha y hora del sistema
        Date hoy = new Date(System.currentTimeMillis());
//        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
//        SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
//
//        System.out.println(date.format(hoy));
//        System.out.println(hour.format(hoy));
//        System.out.println(hoy);
//        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
//        Date fe = new Date(System.currentTimeMillis());
//        Date fe1 = null;
//        
        fechaDe.setMaxSelectableDate(hoy);
        fechaA.setMaxSelectableDate(hoy);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consulta;
    private com.toedter.calendar.JDateChooser fechaA;
    private com.toedter.calendar.JDateChooser fechaDe;
    private javax.swing.JButton imprime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpia;
    private javax.swing.JTextArea muestraR;
    // End of variables declaration//GEN-END:variables
}
